eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaulZone: http://localhost:8761/eureka

zuul:
  routes:
    users:
      path: /users/**
    orders:
      path: /orders/**
    products:
      path: /products/**

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG