server:
  port: 8181

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG

spring:
  application:
    name: products

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 3
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/