Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'false'
      EnableDnsHostnames: 'false'
      InstanceTenancy: default
  SubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: eu-central-1a
      VpcId: !Ref myVPC
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: true
  ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: allow connections from specified CIDR ranges
      VpcId: !Ref myVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0      
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0502e817a62226e03
      SubnetId: !Ref SubnetA
      KeyName: riflik-ec2-access-key-eu-central-1
      UserData:
        'Fn::Base64': 
          !Sub |
            #!/bin/bash -xe
            sudo apt update --yes
            sudo apt install awscli --yes
            sudo apt install default-jre --yes
            sudo curl https://test-jar-hope-it-runs.s3.eu-central-1.amazonaws.com/TestAws.jar -o TestAws.jar
            java -jar TestAws.jar
      SecurityGroupIds:
        - !Ref ServerSecurityGroup
      Tags:
        - Key: Name
          Value: My EC2 Instance
        - Key: Type
          Value: Worker Instance
  EC2TargetGroup:
      Type: AWS::ElasticLoadBalancingV2::TargetGroup
      Properties:
        HealthCheckIntervalSeconds: 30
        HealthCheckProtocol: HTTP
        HealthCheckTimeoutSeconds: 15
        HealthyThresholdCount: 5
        Matcher:
          HttpCode: '200'
        Name: EC2TargetGroup
        Port: 80
        Protocol: HTTP
        TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '20'
        Targets:
        - Id:
            !Ref Ec2Instance
          Port: 80
        UnhealthyThresholdCount: 3
        VpcId:
          !Ref myVPC
        Tags:
        - Key: Name
          Value: EC2TargetGroup
        - Key: Port
          Value: 80
  